import Foundation

struct BadgeDefinition: Identifiable, Codable {
    let id: String
    let name: String
    let milestoneDays: Int
    let imageAssetName: String
    let rarityLevel: String
    let description: String
    let shareQuote: String

    static let defaultBadges: [BadgeDefinition] = [
        BadgeDefinition(id: "day0", name: "Lantern", milestoneDays: 0, imageAssetName: "badge_day0", rarityLevel: "starter", description: "Every journey begins with a single spark. This lantern lights your path through the darkness ahead.", shareQuote: "\"A journey of a thousand miles begins with a single step.\" — Lao Tzu"),
        BadgeDefinition(id: "day1", name: "Apprentice", milestoneDays: 1, imageAssetName: "badge_day1", rarityLevel: "common", description: "You've taken your first step on the path of mastery. The apprentice learns that strength comes from within.", shareQuote: "\"All we have to decide is what to do with the time that is given us.\" — Gandalf"),
        BadgeDefinition(id: "day3", name: "Compass", milestoneDays: 3, imageAssetName: "badge_day3", rarityLevel: "common", description: "Three days of clarity! This compass always points toward your true north, guiding you through temptation.", shareQuote: "\"It is not the strength of the body, but the strength of the spirit.\" — Tolkien"),
        BadgeDefinition(id: "day7", name: "Shield", milestoneDays: 7, imageAssetName: "badge_day7", rarityLevel: "uncommon", description: "A full week of resilience! This shield protects you from the arrows of doubt and craving.", shareQuote: "\"Even the smallest person can change the course of the future.\" — Galadriel"),
        BadgeDefinition(id: "day10", name: "Winglett", milestoneDays: 10, imageAssetName: "badge_day10", rarityLevel: "uncommon", description: "Ten days of new perspective! Winglett the baby hawk spreads curious wings, learning to soar above old patterns. You're rising higher with each passing day.", shareQuote: "\"The only way to discover the limits of the possible is to go beyond them into the impossible.\" — Arthur C. Clarke"),
        BadgeDefinition(id: "day14", name: "Campfire", milestoneDays: 14, imageAssetName: "badge_day14", rarityLevel: "uncommon", description: "Two weeks strong! Gather around this campfire - a place of warmth, rest, and renewed determination.", shareQuote: "\"Courage is not the absence of fear, but acting in spite of it.\" — Mark Twain"),
        BadgeDefinition(id: "day30", name: "Traveler's Sword", milestoneDays: 30, imageAssetName: "badge_day30", rarityLevel: "rare", description: "One month of victory! This sword was forged in the fires of your commitment and tempered by your will.", shareQuote: "\"The only way out is through.\" — Robert Frost"),
        BadgeDefinition(id: "day60", name: "Glint Fox", milestoneDays: 60, imageAssetName: "badge_day60", rarityLevel: "rare", description: "Two months of cunning! Like the Glint Fox, you've learned to outsmart temptation at every turn.", shareQuote: "\"Perseverance is not a long race; it is many short races.\" — Walter Elliot"),
        BadgeDefinition(id: "day90", name: "Crystal Drake", milestoneDays: 90, imageAssetName: "badge_day90", rarityLevel: "epic", description: "Three months of transformation! The Crystal Drake represents your evolution into something truly magnificent.", shareQuote: "\"What we achieve inwardly will change outer reality.\" — Plutarch"),
        BadgeDefinition(id: "day100", name: "Phoenix Guardian", milestoneDays: 100, imageAssetName: "badge_day100", rarityLevel: "epic", description: "100 days of rebirth! Like the Phoenix, you've risen from the ashes, reborn stronger and more radiant than ever.", shareQuote: "\"We are what we repeatedly do. Excellence is not an act, but a habit.\" — Aristotle"),
        BadgeDefinition(id: "day120", name: "Ancient Key", milestoneDays: 120, imageAssetName: "badge_day120", rarityLevel: "legendary", description: "120 days of discovery! This ancient key unlocks the doors to your true potential, doors once thought sealed forever.", shareQuote: "\"The secret of change is to focus all your energy not on fighting the old, but on building the new.\" — Socrates"),
        BadgeDefinition(id: "day150", name: "Leather-bound Map", milestoneDays: 150, imageAssetName: "badge_day150", rarityLevel: "legendary", description: "150 days of exploration! This weathered map charts the territory you've conquered and reveals paths yet to come.", shareQuote: "\"It does not matter how slowly you go as long as you do not stop.\" — Confucius"),
        BadgeDefinition(id: "day180", name: "Obsidian Crown", milestoneDays: 180, imageAssetName: "badge_day180", rarityLevel: "mythic", description: "Half a year of sovereignty! The Obsidian Crown marks you as ruler of your own destiny, unshakeable and resolute.", shareQuote: "\"He who conquers himself is the mightiest warrior.\" — Confucius"),
        BadgeDefinition(id: "day200", name: "Eternal Star Clock", milestoneDays: 200, imageAssetName: "badge_day200", rarityLevel: "mythic", description: "200 days of timeless dedication! The Eternal Star Clock marks the moment when time itself bows to your unwavering resolve.", shareQuote: "\"Stars can't shine without darkness.\" — D.H. Sidebottom"),
        BadgeDefinition(id: "day210", name: "Ancient Forge", milestoneDays: 210, imageAssetName: "badge_day210", rarityLevel: "mythic", description: "210 days of forging! The Ancient Forge glows with primordial fire, where raw determination is hammered into legendary strength.", shareQuote: "\"What is to give light must endure burning.\" — Viktor Frankl"),
        BadgeDefinition(id: "day240", name: "Shroomfolk", milestoneDays: 240, imageAssetName: "badge_day240", rarityLevel: "mythic", description: "240 days of growth! The Shroomfolk emerges from the forest floor, a symbol of resilience thriving in the darkest places.", shareQuote: "\"Out of difficulties grow miracles.\" — Jean de La Bruyère"),
        BadgeDefinition(id: "day270", name: "Steadyhand", milestoneDays: 270, imageAssetName: "badge_day270", rarityLevel: "mythic", description: "270 days of unwavering precision! The Steadyhand bow demands perfect focus. Every arrow finds its mark when your aim is true and steady.", shareQuote: "\"Concentration is the secret of strength.\" — Ralph Waldo Emerson"),
        BadgeDefinition(id: "day300", name: "Stonepip", milestoneDays: 300, imageAssetName: "badge_day300", rarityLevel: "mythic", description: "300 days of joyful resilience! Stonepip, the cheerful pika rabbit, reminds us that strength doesn't mean sacrificing joy. Celebrate every victory with a grateful heart.", shareQuote: "\"Joy is not in things; it is in us.\" — Richard Wagner"),
        BadgeDefinition(id: "day330", name: "Starflare", milestoneDays: 330, imageAssetName: "badge_day330", rarityLevel: "mythic", description: "330 days of cosmic achievement! The Starflare wizard's cloak shimmers like the night sky. You've reached heights once thought impossible, touching the very stars.", shareQuote: "\"Shoot for the moon. Even if you miss, you'll land among the stars.\" — Norman Vincent Peale"),
        BadgeDefinition(id: "day365", name: "Gem of Echoes", milestoneDays: 365, imageAssetName: "badge_day365", rarityLevel: "mythic", description: "One full year of transformation! The Gem of Echoes holds swirling reflections of every choice, every triumph. Each day leaves its mark, creating something mystical and eternal.", shareQuote: "\"We are the sum of all the moments of our lives.\" — Thomas Wolfe"),
        BadgeDefinition(id: "day395", name: "Bramble", milestoneDays: 395, imageAssetName: "badge_day395", rarityLevel: "mythic", description: "395 days of gentle strength! Bramble the hedgehog carries moss and acorns, protected but kind, proving that true resilience comes wrapped in compassion.", shareQuote: "\"In a gentle way, you can shake the world.\" — Mahatma Gandhi"),
        BadgeDefinition(id: "day425", name: "Chronocoin", milestoneDays: 425, imageAssetName: "badge_day425", rarityLevel: "mythic", description: "425 days of temporal mastery! The Chronocoin glows with rotating hourglasses. You've proven that time bends to those who commit fully, body and soul.", shareQuote: "\"Time is the coin of your life. You spend it. Do not allow others to spend it for you.\" — Carl Sandburg"),
        BadgeDefinition(id: "day455", name: "Niblet", milestoneDays: 455, imageAssetName: "badge_day455", rarityLevel: "mythic", description: "455 days of warrior spirit! Niblet the field mouse warrior proves that courage has nothing to do with size. Every giant was once underestimated.", shareQuote: "\"Courage is resistance to fear, mastery of fear—not absence of fear.\" — Mark Twain"),
        BadgeDefinition(id: "day500", name: "Colossus", milestoneDays: 500, imageAssetName: "badge_day500", rarityLevel: "mythic", description: "500 days of immovable strength! The Colossus rests in eternal meditation, a massive stone guardian where moss and wildflowers bloom. Eyes closed with a faint inner glow, you're solid now. Nothing needs proving.", shareQuote: "\"The best fighter is never angry.\" — Lao Tzu"),
        BadgeDefinition(id: "day545", name: "Moonbound", milestoneDays: 545, imageAssetName: "badge_day545", rarityLevel: "mythic", description: "545 days of steadfast guidance! Moonbound glows with midnight fur and soft lunar light, a steady, watchful guardian illuminating your path through the longest nights.", shareQuote: "\"The moon stays bright when it doesn't avoid the night.\" — Rumi"),
        BadgeDefinition(id: "day600", name: "Stillwind", milestoneDays: 600, imageAssetName: "badge_day600", rarityLevel: "mythic", description: "600 days of harmonious mastery! Stillwind, the ancient recorder, channels melodies that echo through time. Each note represents a day conquered, and your song of sobriety resonates across realms.", shareQuote: "\"Where words fail, music speaks.\" — Hans Christian Andersen"),
        BadgeDefinition(id: "day665", name: "Eryndel", milestoneDays: 665, imageAssetName: "badge_day665", rarityLevel: "mythic", description: "665 days of ethereal grace! Eryndel, the mystical elven fairy warrior, embodies timeless strength wrapped in moonlit elegance, proof that true power flows from inner balance and unwavering spirit.", shareQuote: "\"Grace under pressure is the hallmark of a true warrior.\" — Ernest Hemingway"),
        BadgeDefinition(id: "day730", name: "Hopper", milestoneDays: 730, imageAssetName: "badge_day730", rarityLevel: "mythic", description: "Two full years of magical transformation! Hopper the frog wizard reminds us that the greatest metamorphosis happens one day at a time. From tadpole to sorcerer, you've mastered life's most powerful spell: change.", shareQuote: "\"Be the change you wish to see in the world.\" — Mahatma Gandhi"),
        BadgeDefinition(id: "day1095", name: "Spellfeather", milestoneDays: 1095, imageAssetName: "badge_day1095", rarityLevel: "mythic", description: "Three full years of enchanted transformation! Spellfeather glows with ancient magic, a mystical quill that writes your story of triumph. Every word etched with courage, every page turned with purpose.", shareQuote: "\"We write our own destiny. We become what we do.\" — Madame Chiang Kai-Shek"),
        BadgeDefinition(id: "day1460", name: "Hillhold", milestoneDays: 1460, imageAssetName: "badge_day1460", rarityLevel: "mythic", description: "Four full years of enduring sanctuary! Hillhold stands as your fortress of recovery, built into the earth itself. Thick walls, deep roots, and a shelter that cannot be shaken. You've found your home in sobriety.", shareQuote: "\"There is nothing like staying at home for real comfort.\" — Jane Austen"),
        BadgeDefinition(id: "day1825", name: "Foresight", milestoneDays: 1825, imageAssetName: "badge_day1825", rarityLevel: "mythic", description: "Five full years of crystalline clarity! Foresight reveals the path ahead through swirling mist and inner light. With wisdom earned through 1,825 days, you see beyond the present moment into possibilities once hidden.", shareQuote: "\"The best way to predict the future is to create it.\" — Peter Drucker"),
        BadgeDefinition(id: "day2190", name: "Cinderling", milestoneDays: 2190, imageAssetName: "badge_day2190", rarityLevel: "mythic", description: "Six full years of disciplined flame! Cinderling burns with controlled intensity, a small but fierce spirit forged in patience and tempered by time. Each ember represents a day conquered, glowing with inner strength that will never be extinguished.", shareQuote: "\"The most powerful weapon on earth is the human soul on fire.\" — Ferdinand Foch"),
        BadgeDefinition(id: "day2555", name: "Lastlight", milestoneDays: 2555, imageAssetName: "badge_day2555", rarityLevel: "mythic", description: "Seven full years of quiet endurance! Lastlight is a sword worn by time yet still luminous at its core. Not a blade of fury but of resolve. Its softened edges speak of every battle weathered, every temptation turned away. Seven years of choosing the harder, better path.", shareQuote: "\"It does not matter how slowly you go as long as you do not stop.\" — Confucius"),
        BadgeDefinition(id: "day2920", name: "Tidekin", milestoneDays: 2920, imageAssetName: "badge_day2920", rarityLevel: "mythic", description: "Eight full years of flowing strength! Tidekin moves with the calm certainty of deep water. Not rushing, not resisting, just flowing forward with purpose. Eight years of patient, steady progress that carved new channels through once-impossible terrain.", shareQuote: "\"Be like water.\" — Bruce Lee"),
        BadgeDefinition(id: "day3285", name: "Everstack", milestoneDays: 3285, imageAssetName: "badge_day3285", rarityLevel: "mythic", description: "Nine full years of accumulated wisdom! Everstack is a towering monument of knowledge built one day at a time, each volume a chapter of hard-won strength. Ancient and glowing with quiet power, this stack holds every lesson learned, every craving outlasted, every moment of clarity earned through nine years of relentless dedication.", shareQuote: "\"The more that you read, the more things you will know. The more that you learn, the more places you will go.\" — Dr. Seuss")
    ]
    
    /// Returns the display text for the milestone (e.g., "Day 1" or "Start" for day 0)
    var milestoneDisplayText: String {
        milestoneDays == 0 ? "Start" : "Day \(milestoneDays)"
    }
}

